# Training Hyperparameters

device: "auto" # "auto", "cuda", "mps", "cpu"
image_size: 640
# Model Settings
model1:
  encoder: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 2 
  path: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code/roof_estimator/roof_edge_detection_model.pth"

# Model Settings
model2:
  encoder: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 1
  classes: 1 
  path: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code/polygon_estimator/shape_refinment_model.pth"

# Paths
paths:
  base_dir: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code/dataset"
  output_dir: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code"
  train_images: "train_images"
  train_edge_masks: "train_edge_masks"
  train_roof_masks: "train_roof_masks"
  
  valid_images: "valid_images"
  valid_edge_masks: "valid_edge_masks"
  valid_roof_masks: "valid_roof_masks"

  test_images: "test_images"
  test_edge_masks: "test_edge_masks"
  test_roof_masks: "test_roof_masks"

