# Training Hyperparameters
hyperparameters:
  learning_rate: 1.0e-4
  batch_size: 4
  num_epochs: 1
  image_height: 640
  image_width: 640
  num_workers: 0 
  device: "auto" # "auto", "cuda", "mps", "cpu"

# Early Stopping & Scheduler Settings
training_control:
  early_stopping_patience: 8  # Kaç epoch boyunca iyileşme olmazsa dursun
  scheduler_patience: 4        # Kaç epoch iyileşme olmazsa LR düşsün
  scheduler_factor: 0.5        # LR düşürme katsayısı (lr = lr * 0.5)
  min_lr: 1.0e-6

# Model Settings
model:
  encoder_name: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 2 

# Paths
paths:
  base_dir: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code/dataset"
  train_images: "train_images"
  train_edge_masks: "train_edge_masks"
  train_roof_masks: "train_roof_masks"
  
  test_images: "test_images"
  test_edge_masks: "test_edge_masks"
  test_roof_masks: "test_roof_masks"
  
  checkpoint_save_path: "/Users/mert/Documents/PROJECTS/SOLARVIS/train_trials/final_code/roof_estimator/multitask_roof_model_best.pth"